---

- name: Install PostgreSQL
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: postgresql

- name: Create database
  become: true
  become_user: postgres
  postgresql_db: 
    name: "{{etherpad_pgsql_database}}"
    encoding: UTF-8
    lc_collate: es_UY.UTF-8
    lc_ctype: es_UY.UTF-8
    template: template0
    state: present
  tags: postgresql

- name: user has access to the database
  become: true
  become_user: postgres
  postgresql_user: 
    db: "{{etherpad_pgsql_database}}"
    name: "{{etherpad_pgsql_user}}"
    password: "{{etherpad_pgsql_password}}"
    priv: ALL
    state: present
  tags: postgresql

- name: PostgreSQL service is running
  service: 
    name: postgresql
    state: started
    enabled: yes
  tags: postgresql